spring:
  application:
    name: oauth
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      #      ddl-auto: validate
      show-sql: true
    database: MYSQL

  datasource:
    url: jdbc:mysql://localhost:3306/google?serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/ims
    username: root
    password:
    validation-query: SELECT 1

google:
  client:
    clientId: 638895535747-elon4ncm44m3gdnhk4t1jp2bskja6sgq.apps.googleusercontent.com
    clientSecret: yGuh44sl0Zhq9xlAenjgHmXb
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: email, profile

  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo




logging:
  level:
    org.hibernate.type: trace